# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FitnessTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FitnessTracker
  pod 'RxSwift', '4.0.0-beta.1'
  pod 'RxCocoa', '4.0.0-beta.1'
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'UIGraphView', :path => '../'
  
  target 'FitnessTrackerTests' do
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
    pod 'RxTest', '4.0.0-beta.1'
  end
end

