# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FitnessTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FitnessTracker
  pod 'RxSwift'
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'RxCocoa'
  pod 'UIGraphView', :path => '../'
  
  target 'FitnessTrackerTests' do
    pod 'Quick'
    pod 'Nimble'
    pod 'RxTest'
  end
end

